spring.application.name=Desafio1

spring.datasource.url=jdbc:mysql://localhost:3306/desafio1?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=never
server.port=8080